#!/bin/bash
# Quick Start Guide for Fly Mixxx

echo "🎵 Fly Mixxx - DJ Mixer Application"
echo "===================================="
echo ""
echo "✅ Installation steps:"
echo ""
echo "1. Install Flutter (if not installed)"
echo "   https://flutter.dev/docs/get-started/install"
echo ""
echo "2. Clone repository"
echo "   git clone <repository-url>"
echo "   cd new_fly_mixxxx"
echo ""
echo "3. Get dependencies"
echo "   flutter pub get"
echo ""
echo "4. Run application"
echo ""
echo "   For Windows:"
echo "   flutter run -d windows"
echo ""
echo "   For Android:"
echo "   flutter run -d android"
echo ""
echo "5. Build for production"
echo ""
echo "   Windows:"
echo "   flutter build windows --release"
echo ""
echo "   Android:"
echo "   flutter build apk --release"
echo ""
echo "===================================="
echo "📚 Documentation:"
echo "  - User docs: ./docs/user/"
echo "  - Dev docs: ./docs/developer/"
echo ""
echo "🎪 New Features:"
echo "  - EQ Preset Carousel (9 genres)"
echo "  - Audio Device Analysis"
echo "  - Composition Generator with API selection"
echo ""
echo "Happy mixing! 🎧"

